db.getCollection("Examples").find({})
//db.Examples.find({ShipperID:3})
//db.Examples.find({ShipperID:{$lt:3}})
//db.Examples.find({ShipperID:{$in:[1,3]}})
//db.Examples.find({$or:[{CompanyName:'United Package'},{CompanyName:'Speedy Express'}]})
//db.Examples.insert({ShipperID:4,CompanyName:'ExpressDelivery',Phone:'(+48)777-888-999'})
//db.Examples.find({ShipperID:4})
//db.Examples.update({'ShipperID':4},{$set:{'ShipperID':57}})
//db.Examples.find({ShipperID:4})
//db.Examples.find({ShipperID:57})
//db.Examples.remove({ShipperID:57})